[package]
name = "例9-5"
version = "0.1.0"
authors = ["caihui-1987 <68584593+caihui-1987@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
